version: '3'
services:
  ReactJS:
    image: node:19.0.0-alpine
    working_dir: /app
    tty: true
    stdin_open: true
    volumes:
      - ./front:/app
    container_name: ReactJS
    ports:
      - '3000:3000'
    depends_on:
      - backend 
    command: npm start

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - './backend:/app'
    container_name: Express

  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
